In [6]:
# Comprehensive File Operations in Python (Fully Commented)

"""
This script demonstrates various file operations in Python, including:
- Text file operations (reading, writing, appending)
- Binary file operations
- CSV file handling (with and without pandas)
- File system operations (checking existence, getting info, listing, removing)

It's designed to run in any environment, including Google Colab.
"""

import os
import csv
import struct

# Create a sample text file for our operations
with open('example.txt', 'w') as file:
    file.write("This is the first line.\nThis is the second line.\nThis is the third line.")

# 1. Reading an entire file at once
print("1. Reading a file:")
with open('example.txt', 'r') as file:
    content = file.read()  # Read the entire file content
    print(content)

# 2. Reading a file line by line
print("\n2. Reading a file line by line:")
with open('example.txt', 'r') as file:
    for line in file:
        # strip() removes leading/trailing whitespace, including newline characters
        print(line.strip())

# 3. Writing to a new file
print("\n3. Writing to a file:")
with open('output.txt', 'w') as file:  # 'w' mode creates a new file or overwrites existing
    file.write("This is a new line.\n")
    file.write("This is another line.\n")
print("File 'output.txt' has been created.")

# 4. Appending to an existing file
print("\n4. Appending to a file:")
with open('output.txt', 'a') as file:  # 'a' mode appends to the file
    file.write("This line is appended.\n")
print("Content appended to 'output.txt'.")

# 5. Binary file operations
print("\n5. Binary file operations:")
binary_file_name = 'binary_file.bin'

# Writing to a binary file
# struct.pack converts Python values to a bytes object
data_to_write = struct.pack('4f', 3.14, 2.718, 1.414, 0.577)
with open(binary_file_name, 'wb') as file:  # 'wb' mode for writing binary
    file.write(data_to_write)
print(f"Binary data written to {binary_file_name}")

# Reading from a binary file
with open(binary_file_name, 'rb') as file:  # 'rb' mode for reading binary
    binary_content = file.read()
    # struct.unpack converts bytes to Python values
    unpacked_data = struct.unpack('4f', binary_content)
    print(f"Read binary data: {unpacked_data}")

# 6. CSV file operations using csv module
print("\n6. CSV file operations:")
csv_file_name = 'data.csv'

# Writing to a CSV file
data_to_write = [
    ['Name', 'Age', 'City'],
    ['Alice', 30, 'New York'],
    ['Bob', 25, 'Los Angeles'],
    ['Charlie', 35, 'Chicago']
]

with open(csv_file_name, 'w', newline='') as file:
    writer = csv.writer(file)
    writer.writerows(data_to_write)  # Write all rows at once
print(f"CSV data written to {csv_file_name}")

# Reading from a CSV file
print("Contents of the CSV file:")
with open(csv_file_name, 'r') as file:
    reader = csv.reader(file)
    for row in reader:
        print(row)

# 7. CSV operations with Pandas (if available)
try:
    import pandas as pd
    print("\n7. CSV operations with Pandas:")

    # Creating a DataFrame and writing to CSV
    df = pd.DataFrame(data_to_write[1:], columns=data_to_write[0])
    pandas_csv_file = 'pandas_data.csv'
    df.to_csv(pandas_csv_file, index=False)
    print(f"DataFrame written to {pandas_csv_file}")

    # Reading CSV with Pandas
    df_read = pd.read_csv(pandas_csv_file)
    print("DataFrame read from CSV:")
    print(df_read)

except ImportError:
    print("\n7. Pandas not available. Skipping Pandas CSV operations.")

# 8. File existence and information
print("\n8. File information:")
for file_name in [binary_file_name, csv_file_name]:
    if os.path.exists(file_name):  # Check if file exists
        file_stats = os.stat(file_name)  # Get file statistics
        print(f"'{file_name}' exists. Size: {file_stats.st_size} bytes, "
              f"Last modified: {file_stats.st_mtime}")
    else:
        print(f"'{file_name}' does not exist.")

# 9. Listing and removing files
print("\n9. Listing and removing files:")
files_to_remove = [binary_file_name, csv_file_name]
if 'pandas_csv_file' in locals():
    files_to_remove.append(pandas_csv_file)

print("Files in the current directory:")
for file in os.listdir('.'):  # List all files in current directory
    if os.path.isfile(file):  # Check if it's a file (not a directory)
        print(file)

# Remove files we created
for file in files_to_remove:
    if os.path.exists(file):
        os.remove(file)  # Delete the file
        print(f"Removed: {file}")

print("\nRemaining files in the current directory:")
for file in os.listdir('.'):
    if os.path.isfile(file):
        print(file)

"""
Key takeaways:
1. Use 'with' statements for automatic file closing.
2. Different modes for different operations: 'r' for read, 'w' for write, 'a' for append.
3. Binary files use 'b' in the mode (e.g., 'rb', 'wb').
4. The csv module simplifies CSV file operations.
5. Pandas offers powerful tools for data manipulation and CSV handling.
6. Always check file existence before operations to avoid errors.
7. Use os module for file system operations like checking existence, getting info, and removing files.
"""

1. Reading a file:
This is the first line.
This is the second line.
This is the third line.

2. Reading a file line by line:
This is the first line.
This is the second line.
This is the third line.

3. Writing to a file:
File 'output.txt' has been created.

4. Appending to a file:
Content appended to 'output.txt'.

5. Binary file operations:
Binary data written to binary_file.bin
Read binary data: (3.140000104904175, 2.7179999351501465, 1.4140000343322754, 0.5770000219345093)

6. CSV file operations:
CSV data written to data.csv
Contents of the CSV file:
['Name', 'Age', 'City']
['Alice', '30', 'New York']
['Bob', '25', 'Los Angeles']
['Charlie', '35', 'Chicago']

7. CSV operations with Pandas:
DataFrame written to pandas_data.csv
DataFrame read from CSV:
      Name  Age         City
0    Alice   30     New York
1      Bob   25  Los Angeles
2  Charlie   35      Chicago

8. File information:
'binary_file.bin' exists. Size: 16 bytes, Last modified: 1728534313.5024526
'data.csv' exists. Si

"\nKey takeaways:\n1. Use 'with' statements for automatic file closing.\n2. Different modes for different operations: 'r' for read, 'w' for write, 'a' for append.\n3. Binary files use 'b' in the mode (e.g., 'rb', 'wb').\n4. The csv module simplifies CSV file operations.\n5. Pandas offers powerful tools for data manipulation and CSV handling.\n6. Always check file existence before operations to avoid errors.\n7. Use os module for file system operations like checking existence, getting info, and removing files.\n"

# Python File Operations: Key Points and Practice Exercises

## Key Points to Remember:

1. File Handling Basics:
   - Always close files after opening them, or use the `with` statement for automatic closure.
   - Use appropriate file modes: 'r' for reading, 'w' for writing (overwrites existing content), 'a' for appending.
   - For binary files, add 'b' to the mode (e.g., 'rb', 'wb').

2. Binary File Operations:
   - The 'struct' module is useful for packing and unpacking binary data.

3. CSV File Handling:
   - The csv module provides convenient ways to work with CSV files.
   - For advanced operations, consider using pandas if available.

4. File System Operations:
   - Use `os.path.exists()` to check if a file exists before trying to open it.
   - `os.stat()` provides useful information about files.
   - `os.listdir()` can be used to get a list of files in a directory.
   - Be careful when using `os.remove()` as it permanently deletes files.

5. Best Practices:
   - Always check file existence before operations to avoid errors.
   - Use appropriate error handling, especially when working with files or importing optional libraries.
   - Clean up temporary files after operations to manage storage efficiently.

## Practice Exercises:

1. Text File Processing:
   - Create a function that reads a text file and counts the occurrences of each word.
   - Implement a simple log file writer that appends timestamped entries.

2. Binary File Operations:
   - Create a binary file containing a mix of integers, floats, and strings. Read and parse this file.
   - Implement a file compression/decompression utility using binary file operations.

3. CSV File Handling:
   - Write a script that merges multiple CSV files into a single file.
   - Create a script that reads a CSV file, performs some data analysis, and writes the results to a new CSV file.

4. Advanced Data Processing:
   - Create a data processing pipeline that reads from multiple CSV files, merges the data, and outputs a single binary file.

5. File System Management:
   - Create a file backup system that copies important files to a backup directory.
   - Implement a script that organizes files in a directory based on their extension or creation date.

These exercises cover a range of file operation tasks, from basic text processing to advanced data handling, and will help reinforce the key concepts of file I/O in Python.

In [14]:
# Introduction to Pandas: 10-Minute Explanation with File Creation

"""
This script demonstrates key concepts of Pandas, a powerful Python library for data manipulation and analysis.
It includes examples of creating, reading, and manipulating data using Pandas, along with necessary file creation.

Key concepts covered:
1. Series and DataFrame creation
2. Reading and writing data
3. Data selection and filtering
4. Data manipulation
5. Basic statistics and aggregation
"""

import pandas as pd
import numpy as np
import os

# Create necessary files

# Create a CSV file for later use
csv_data = """Name,Age,City
John,30,New York
Alice,25,Los Angeles
Bob,35,Chicago
"""
with open('data.csv', 'w') as f:
    f.write(csv_data)
print("'data.csv' file created.")

# 1. Creating a Pandas Series
print("\n1. Pandas Series:")
# Create a Series with some sample data, including a NaN value
s = pd.Series([1, 3, 5, np.nan, 6, 8])
print(s)
# Series is a one-dimensional labeled array that can hold data of any type

# 2. Creating a DataFrame
print("\n2. Pandas DataFrame:")
# Create a date range for the index
dates = pd.date_range('20230101', periods=6)
# Create a DataFrame with random values, dates as index, and columns labeled A, B, C, D
df = pd.DataFrame(np.random.randn(6, 4), index=dates, columns=list('ABCD'))
print(df)
# DataFrame is a 2-dimensional labeled data structure with columns of potentially different types

# 3. Reading data from CSV
print("\n3. Reading CSV:")
# Read the CSV file we created earlier
df_csv = pd.read_csv('data.csv')
print(df_csv)

# 4. Basic information about the DataFrame
print("\n4. DataFrame Info:")
# Display information about the DataFrame, including column names and data types
print(df.info())
print("\nDataFrame Description:")
# Generate descriptive statistics of the DataFrame
print(df.describe())

# 5. Selection and indexing
print("\n5. Selection and Indexing:")
print("First two rows of column A:")
# Select the first two rows of column A
print(df['A'].head(2))
print("\nSlicing the DataFrame:")
# Select rows 1 to 2 (exclusive of 3) of all columns
print(df[1:3])

# 6. Filtering data
print("\n6. Filtering Data:")
print("Rows where A > 0:")
# Select rows where the value in column A is greater than 0
print(df[df['A'] > 0])

# 7. Adding a new column
# Add a new column 'E' with categorical data
df['E'] = ['one', 'one', 'two', 'three', 'four', 'three']
print("\n7. DataFrame with new column:")
print(df)

# 8. Grouping and aggregating
print("\n8. Grouping and Aggregating:")
# Group by column E and calculate the mean of other columns for each group
print(df.groupby('E').mean())

# 9. Handling missing data
print("\n9. Handling Missing Data:")
# Introduce a NaN value in the DataFrame
df.loc[dates[0], 'A'] = np.nan
print("DataFrame with NaN:")
print(df)
print("\nDropping NaN values:")
# Remove rows with any NaN values
print(df.dropna())

# 10. Merging DataFrames
print("\n10. Merging DataFrames:")
# Create two sample DataFrames
df1 = pd.DataFrame({'A': ['A0', 'A1', 'A2'],
                    'B': ['B0', 'B1', 'B2']},
                    index=['K0', 'K1', 'K2'])

df2 = pd.DataFrame({'C': ['C0', 'C1', 'C2'],
                    'D': ['D0', 'D1', 'D2']},
                    index=['K0', 'K2', 'K3'])

print("Merged DataFrame:")
# Concatenate the two DataFrames along the columns axis
print(pd.concat([df1, df2], axis=1))

# Clean up: remove the created CSV file
#os.remove('data.csv')
#print("\nTemporary 'data.csv' file removed.")

"""
Key points to remember:
1. Pandas provides powerful data structures: Series (1D) and DataFrame (2D).
2. It offers various methods for reading data from different sources (CSV, Excel, SQL databases, etc.).
3. Data selection, filtering, and manipulation are straightforward with Pandas.
4. Pandas integrates well with NumPy and other scientific Python libraries.
5. It provides built-in functions for handling missing data and performing basic statistical operations.

Practice suggestions:
1. Load a large CSV file and perform basic data cleaning operations.
2. Implement a data analysis task involving grouping, aggregation, and visualization.
3. Experiment with different data manipulation methods like pivot tables and melting/stacking.
"""

'data.csv' file created.

1. Pandas Series:
0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

2. Pandas DataFrame:
                   A         B         C         D
2023-01-01 -0.123328 -1.015910 -1.432692 -0.955937
2023-01-02  0.538828  0.179265  0.908856  0.439610
2023-01-03 -2.495035 -0.385930  1.795907  0.990131
2023-01-04  0.302800  1.323210  0.352103  0.274582
2023-01-05 -1.736555  0.353795  1.274550  1.812729
2023-01-06 -0.317349  0.338418  0.001349  0.015034

3. Reading CSV:
    Name  Age         City
0   John   30     New York
1  Alice   25  Los Angeles
2    Bob   35      Chicago

4. DataFrame Info:
<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 6 entries, 2023-01-01 to 2023-01-06
Freq: D
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   A       6 non-null      float64
 1   B       6 non-null      float64
 2   C       6 non-null      float64
 3   D       6 non-null      float64
dtypes: floa

'\nKey points to remember:\n1. Pandas provides powerful data structures: Series (1D) and DataFrame (2D).\n2. It offers various methods for reading data from different sources (CSV, Excel, SQL databases, etc.).\n3. Data selection, filtering, and manipulation are straightforward with Pandas.\n4. Pandas integrates well with NumPy and other scientific Python libraries.\n5. It provides built-in functions for handling missing data and performing basic statistical operations.\n\nPractice suggestions:\n1. Load a large CSV file and perform basic data cleaning operations.\n2. Implement a data analysis task involving grouping, aggregation, and visualization.\n3. Experiment with different data manipulation methods like pivot tables and melting/stacking.\n'

In [15]:
# Introduction to NumPy: 10-Minute Explanation (Fully Commented)

"""
NumPy (Numerical Python) is a fundamental package for scientific computing in Python.
It provides support for large, multi-dimensional arrays and matrices, along with a
collection of mathematical functions to operate on these arrays efficiently.

Key concepts:
1. NumPy arrays
2. Array creation and manipulation
3. Mathematical operations
4. Broadcasting
5. Indexing and slicing
6. Linear algebra operations
"""

import numpy as np

# 1. Creating NumPy arrays
print("1. Creating NumPy arrays:")
# Create a 1D array
a = np.array([1, 2, 3, 4, 5])
# Create a 2D array
b = np.array([[1, 2, 3], [4, 5, 6]])
print("1D array:", a)
print("2D array:\n", b)

# 2. Array attributes
print("\n2. Array attributes:")
# Shape returns the dimensions of the array
print("Shape of b:", b.shape)
# ndim returns the number of dimensions
print("Dimension of b:", b.ndim)
# dtype returns the data type of the array elements
print("Data type of b:", b.dtype)

# 3. Array creation functions
print("\n3. Array creation functions:")
# Create a 2x3 array of zeros
c = np.zeros((2, 3))
# Create a 2x2 array of ones
d = np.ones((2, 2))
# Create an array of integers from 0 to 9
e = np.arange(10)
# Create an array of 5 evenly spaced numbers between 0 and 1
f = np.linspace(0, 1, 5)
print("Zeros:\n", c)
print("Ones:\n", d)
print("Arange:", e)
print("Linspace:", f)

# 4. Basic operations
print("\n4. Basic operations:")
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
# Element-wise addition
print("a + b =", a + b)
# Element-wise multiplication
print("a * b =", a * b)
# Element-wise exponentiation
print("a ** 2 =", a ** 2)

# 5. Broadcasting
print("\n5. Broadcasting:")
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([10, 20, 30])
# Broadcasting allows operations on arrays with different shapes
print("a + b =\n", a + b)

# 6. Indexing and slicing
print("\n6. Indexing and slicing:")
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print("Original array:\n", a)
# Access a single element
print("Element at (1,2):", a[1, 2])
# Access an entire row
print("Second row:", a[1, :])
# Access an entire column
print("Second column:", a[:, 1])
# Access a subarray
print("Subarray:\n", a[0:2, 1:3])

# 7. Reshaping arrays
print("\n7. Reshaping arrays:")
a = np.arange(12)
print("Original:", a)
# Reshape the 1D array into a 3x4 2D array
b = a.reshape((3, 4))
print("Reshaped:\n", b)

# 8. Mathematical functions
print("\n8. Mathematical functions:")
a = np.array([0, np.pi/2, np.pi])
# Apply sine function element-wise
print("Sin:", np.sin(a))
# Apply exponential function element-wise
print("Exp:", np.exp(a))
# Apply square root function element-wise
print("Sqrt:", np.sqrt(a))

# 9. Aggregation functions
print("\n9. Aggregation functions:")
a = np.array([[1, 2, 3], [4, 5, 6]])
# Sum of all elements in the array
print("Sum of all elements:", np.sum(a))
# Mean of each column (axis=0 refers to columns)
print("Mean of each column:", np.mean(a, axis=0))
# Maximum value in each row (axis=1 refers to rows)
print("Max of each row:", np.max(a, axis=1))

# 10. Linear algebra
print("\n10. Linear algebra:")
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
# Matrix multiplication
print("Matrix multiplication:\n", np.dot(a, b))
# Compute the determinant of a matrix
print("Determinant:", np.linalg.det(a))
# Compute the eigenvalues of a matrix
print("Eigenvalues:", np.linalg.eigvals(a))

"""
Key points to remember:
1. NumPy arrays are the foundation of numerical computing in Python.
2. NumPy operations are generally faster than equivalent Python code, especially for large arrays.
3. Broadcasting allows operations between arrays of different shapes.
4. NumPy provides a wide range of mathematical and statistical functions.
5. Linear algebra operations are efficiently implemented in NumPy.

Practice:
1. Implement a simple image processing task using NumPy arrays.
2. Solve a system of linear equations using NumPy's linear algebra module.
3. Perform element-wise operations on large arrays and compare performance with pure Python.
"""

1. Creating NumPy arrays:
1D array: [1 2 3 4 5]
2D array:
 [[1 2 3]
 [4 5 6]]

2. Array attributes:
Shape of b: (2, 3)
Dimension of b: 2
Data type of b: int64

3. Array creation functions:
Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]
Ones:
 [[1. 1.]
 [1. 1.]]
Arange: [0 1 2 3 4 5 6 7 8 9]
Linspace: [0.   0.25 0.5  0.75 1.  ]

4. Basic operations:
a + b = [5 7 9]
a * b = [ 4 10 18]
a ** 2 = [1 4 9]

5. Broadcasting:
a + b =
 [[11 22 33]
 [14 25 36]]

6. Indexing and slicing:
Original array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Element at (1,2): 7
Second row: [5 6 7 8]
Second column: [ 2  6 10]
Subarray:
 [[2 3]
 [6 7]]

7. Reshaping arrays:
Original: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

8. Mathematical functions:
Sin: [0.0000000e+00 1.0000000e+00 1.2246468e-16]
Exp: [ 1.          4.81047738 23.14069263]
Sqrt: [0.         1.25331414 1.77245385]

9. Aggregation functions:
Sum of all elements: 21
Mean of each column: [2.5 3.5 4.5]
Ma

"\nKey points to remember:\n1. NumPy arrays are the foundation of numerical computing in Python.\n2. NumPy operations are generally faster than equivalent Python code, especially for large arrays.\n3. Broadcasting allows operations between arrays of different shapes.\n4. NumPy provides a wide range of mathematical and statistical functions.\n5. Linear algebra operations are efficiently implemented in NumPy.\n\nPractice:\n1. Implement a simple image processing task using NumPy arrays.\n2. Solve a system of linear equations using NumPy's linear algebra module.\n3. Perform element-wise operations on large arrays and compare performance with pure Python.\n"


Implement an Object-Oriented Student Course Management System using Python, incorporating file I/O operations, Pandas for data manipulation, and NumPy for numerical computations.

## Requirements:

1. Create the following classes:
   - `Student`
   - `Course`
   - `CourseManagementSystem`

2. Use appropriate data structures within these classes:
   - Pandas DataFrame to store Student and Course information
   - NumPy arrays for numerical computations (e.g., GPA calculation)

3. Implement the following methods in the `CourseManagementSystem` class:
   - `add_student(name: str, student_id: int)`
   - `add_course(code: str, name: str, credits: int, capacity: int)`
   - `enroll_student(student_id: int, course_code: str)`
   - `calculate_total_credits(student_id: int) -> int`
   - `find_students_in_course(course_code: str) -> List[str]`
   - `get_most_popular_course() -> str`
   - `remove_course(course_code: str)`
   - `calculate_gpa(student_id: int) -> float`
   - `get_student_courses(student_id: int) -> List[str]`
   - `add_to_waitlist(student_id: int, course_code: str)`

4. Implement file I/O operations:
   - Load initial student and course data from CSV files
   - Save updated student and course information to CSV files after each operation
   - Implement a logging system that writes operation logs to a text file

5. Use Pandas for data manipulation:
   - Store student and course information in Pandas DataFrames
   - Use Pandas functions for filtering, grouping, and aggregating data

6. Use NumPy for numerical computations:
   - Calculate GPA using NumPy arrays and functions
   - Use NumPy for any other relevant numerical operations (e.g., course statistics)

7. Implement proper exception handling for scenarios such as:
   - File I/O errors
   - Data format errors in CSV files
   - Enrolling a student in a non-existent course
   - Enrolling a student in a course that's already full

8. Add a grading system to the `Student` class and use it to calculate GPA using NumPy.

9. Implement a waitlist system for courses that are full, storing waitlist data in a separate CSV file.

## Learning Objectives:
By completing this assignment, you should be able to:
- Design and implement a system using object-oriented programming principles
- Utilize Pandas for efficient data manipulation and analysis
- Apply NumPy for numerical computations in a real-world scenario
- Implement file I/O operations for data persistence and logging
- Handle exceptions to make the system more robust

## Tasks:
1. Implement the classes and methods as described.
2. Write functions to load and save data using CSV files and Pandas.
3. Implement GPA calculation using NumPy arrays.
4. Create a main function that demonstrates all the features of your system, including file I/O operations.
5. Add comprehensive error handling and logging.
6. Write a brief explanation of how you've used each of the following in your implementation:
   - Classes and objects
   - File I/O operations
   - Pandas for data manipulation
   - NumPy for numerical computations
   - Exception handling
7. Suggest one improvement or additional feature for this system and explain how you would implement it using the tools and libraries mentioned.

## Submission Guidelines:
- Submit your Python script(s) containing the implementation of the Student Course Management System.
- Include sample CSV files for initial student and course data.
- Provide a separate document with your explanations and suggestions as requested in tasks 6 and 7.
- Ensure your code is well-commented and follows Python best practices for readability and style.


## Grading Criteria:
- Correct implementation of all required classes and methods (30%)
- Proper use of Pandas and NumPy (20%)
- Effective implementation of file I/O operations and data persistence (15%)
- Appropriate use of exception handling and logging (10%)
- Code organization, readability, and adherence to Python best practices (10%)
- Successful demonstration of system functionality, including file operations (10%)
- Quality of explanations and improvement suggestions (5%)

Bonus points may be awarded for:
- Implementation of additional features beyond the basic requirements
- Particularly efficient or elegant solutions to complex problems
- Comprehensive test cases that cover various scenarios

Total: 100% (with possibility of bonus points)

Note: Partial credit may be given for incomplete implementations that demonstrate understanding of the core concepts.